name: Build and Submit Dependencies

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn clean install

      - name: Submit dependency snapshot
        uses: advanced-security/maven-dependency-submission-action@v1
